In [1]:
import pandas as pd
import numpy as np
import config

In [2]:
train = pd.read_csv(config.DATA_DIR + "mnist_train.csv")
train

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0          5    0    0    0    0    0    0    0    0    0  ...      0      0   
1          0    0    0    0    0    0    0    0    0    0  ...      0      0   
2          4    0    0    0    0    0    0    0    0    0  ...      0      0   
3          1    0    0    0    0    0    0    0    0    0  ...      0      0   
4          9    0    0    0    0    0    0    0    0    0  ...      0      0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
59995      8    0    0    0    0    0    0    0    0    0  ...      0      0   
59996      3    0    0    0    0    0    0    0    0    0  ...      0      0   
59997      5    0    0    0    0    0    0    0    0    0  ...      0      0   
59998      6    0    0    0    0    0    0    0    0    0  ...      0      0   
59999      8    0    0    0    0    0    0    0    0    0  ...      0      0   

       28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
59995      0      0      0      0      0      0      0      0  
59996      0      0      0      0      0      0      0      0  
59997      0      0      0      0      0      0      0      0  
59998      0      0      0      0      0      0      0      0  
59999      0      0      0      0      0      0      0      0  

[60000 rows x 785 columns]

In [3]:
test = pd.read_csv(config.DATA_DIR + "mnist_test.csv")
test

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0         7    0    0    0    0    0    0    0    0    0  ...      0      0   
1         2    0    0    0    0    0    0    0    0    0  ...      0      0   
2         1    0    0    0    0    0    0    0    0    0  ...      0      0   
3         0    0    0    0    0    0    0    0    0    0  ...      0      0   
4         4    0    0    0    0    0    0    0    0    0  ...      0      0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
9995      2    0    0    0    0    0    0    0    0    0  ...      0      0   
9996      3    0    0    0    0    0    0    0    0    0  ...      0      0   
9997      4    0    0    0    0    0    0    0    0    0  ...      0      0   
9998      5    0    0    0    0    0    0    0    0    0  ...      0      0   
9999      6    0    0    0    0    0    0    0    0    0  ...      0      0   

      28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0         0      0      0      0      0      0      0      0  
1         0      0      0      0      0      0      0      0  
2         0      0      0      0      0      0      0      0  
3         0      0      0      0      0      0      0      0  
4         0      0      0      0      0      0      0      0  
...     ...    ...    ...    ...    ...    ...    ...    ...  
9995      0      0      0      0      0      0      0      0  
9996      0      0      0      0      0      0      0      0  
9997      0      0      0      0      0      0      0      0  
9998      0      0      0      0      0      0      0      0  
9999      0      0      0      0      0      0      0      0  

[10000 rows x 785 columns]

In [4]:
X_train = (train.iloc[:, 1:].T / 255).values
y_train = (train.iloc[:, [0]].T).values
# y_train = pd.get_dummies(y_train.iloc[0, :]).T.values
display(X_train)
display(y_train)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

array([[5, 0, 4, ..., 5, 6, 8]])

In [5]:
X_test = (test.iloc[:, 1:].T / 255).values
y_test = test.iloc[:, [0]].T.values
# y_test = pd.get_dummies(y_test.iloc[0, :]).T.values
display(X_test)
display(y_test)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

array([[7, 2, 1, ..., 4, 5, 6]])

In [34]:
class Linear:
    def __init__(self, input_size, output_size):
        self.w = np.random.rand(output_size, input_size) / input_size
        self.b = np.random.rand(output_size, 1) / input_size
        
    def forward(self, X):
        """
        X = (n_i, m)
        """
        self.input = X
        return np.dot(self.w, X) + self.b
    
    def backward(self, grad):
        """
        grad is partial derivative of the cost function wrt the output of the linear layer.
        grad = (n_o, m)
        Returns partial derivative of the cost function wrt the input of the linear layer.
        """
#         print('backward linear')
        # (n_o, m) * (m, n_i) = (n_o, n_i)
        self.weight_grad = np.dot(grad, self.input.T)
        # (n_o, m)
        self.bias_grad = np.sum(grad, axis=1, keepdims=True)
        # (n_i, n_o) * (n_o, m) = (n_i, m)
        return np.dot(self.w.T, grad)
    
    def step(self, alpha):
        """
            Subtracts alpha * gradient from weights
        """
        self.w = self.w - alpha * self.weight_grad
        self.b = self.b - alpha * self.bias_grad

In [35]:
class Sigmoid:
    def __init__(self):
        pass
    
    def forward(self, z):
        # (n_i, m)
        self.output = 1 / (1 + np.exp(-1 * z)) 
        return self.output
    
    def backward(self, grad):
#         print('backward sigmoid')
        # (n_i, m) 
        return self.output * (1 - self.output) * grad

    def step(self, alpha):
        """Does nothing"""
        pass

In [36]:
class MSE:
    def __init__(self):
        pass
    
    def forward(self, y, y_hat):
        return np.square(y - y_hat)
    
    def backward(self, y, y_hat):
        """
            Returns partial derivative of cost function
            wrt y_hat
        """
        return -2 * (y - y_hat)

In [37]:
class Net:
    def __init__(self, layers):
        self.layers = layers
        self.mse = MSE()
        
    def forward(self, X):
        y_hat = X
        for layer in self.layers:
            y_hat = layer.forward(y_hat)
        return y_hat
    
    def backward(self, grad):
        """
            Grad is partial derivative of cost function wrt to y_hat
        """
        for layer in self.layers[::-1]:
            grad = layer.backward(grad)
            
    def step(self, alpha):
        for layer in self.layers:
            layer.step(alpha)
    
    def fit(self, X, y, epochs=30, mini_batch_size=10, alpha=0.03, test_data=None):
        y = pd.get_dummies(y[0, :]).T.values
        for epoch in range(epochs):
            for minibatch in self.get_minibatches(X, y, mini_batch_size):
                X_batch, y_batch = minibatch
                y_hat = self.forward(X_batch)
                grad = self.mse.backward(y_batch, y_hat)
                self.backward(grad)
                self.step(alpha)
            print("End epoch", str(epoch), )
            if test_data is not None:
                print("Accuracy:", self.score(test_data[0], test_data[1]))
                
    def predict(self, X):
        y_hat = self.forward(X)
        predictions = np.argmax(y_hat, axis=0)
        return predictions
        
    def score(self, X, y):
        """Returns accuracy"""
        predictions = self.predict(X)
        accuracy = (y == predictions).sum(axis=0).mean()
        return accuracy
    
    def get_minibatches(self, X, y, mini_batch_size):
        m = X.shape[1]
        perm = np.random.permutation(m)
        mini_batches = []
        for start_idx in range(0, m, mini_batch_size):
            end_idx = min(start_idx + mini_batch_size, m - 1)
            X_batch = X[:, start_idx:end_idx]
            y_batch = y[:, start_idx:end_idx]
            mini_batches.append((X_batch, y_batch))
        return mini_batches

In [38]:
net = Net([
    Linear(784, 30),
    Sigmoid(),
    Linear(30, 10),
    Sigmoid()
])
net.fit(X_train, y_train, test_data=(X_test, y_test))

End epoch 0
Accuracy: 0.9174
End epoch 1
Accuracy: 0.9349
End epoch 2
Accuracy: 0.9431
End epoch 3
Accuracy: 0.9466
End epoch 4
Accuracy: 0.95
End epoch 5
Accuracy: 0.952
End epoch 6
Accuracy: 0.9535
End epoch 7
Accuracy: 0.9548
End epoch 8
Accuracy: 0.9564
End epoch 9
Accuracy: 0.9575
End epoch 10
Accuracy: 0.9579
End epoch 11
Accuracy: 0.9581
End epoch 12
Accuracy: 0.9583
End epoch 13
Accuracy: 0.9584
End epoch 14
Accuracy: 0.9586
End epoch 15
Accuracy: 0.9589
End epoch 16
Accuracy: 0.9594
End epoch 17
Accuracy: 0.9599
End epoch 18
Accuracy: 0.9596
End epoch 19
Accuracy: 0.9598
End epoch 20
Accuracy: 0.9597
End epoch 21
Accuracy: 0.9596
End epoch 22
Accuracy: 0.9599
End epoch 23
Accuracy: 0.96
End epoch 24
Accuracy: 0.9601
End epoch 25
Accuracy: 0.9604
End epoch 26
Accuracy: 0.9601
End epoch 27
Accuracy: 0.9603
End epoch 28
Accuracy: 0.9605
End epoch 29
Accuracy: 0.9606
